INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('barneykatakwa@gmail.com','Barnabas','Katakwa','My Name is Barnabas Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('tkaluzi@gmail.com','Tapiwa','Kaluzi','My Name is Tapiwa Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('nchimombe@gmail.com','Barnabas','Katakwa','My Name is Barnabas Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('slusaka@gmail.com','South','Lusaka','My Name is South Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('barneykatakwa@gmail.com','Barnabas','Katakwa','My Name is Barnabas Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('tkaluzi@gmail.com','Tapiwa','Kaluzi','My Name is Tapiwa Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('nchimombe@gmail.com','Barnabas','Katakwa','My Name is Barnabas Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('slusaka@gmail.com','South','Lusaka','My Name is South Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('barneykatakwa@gmail.com','Barnabas','Katakwa','My Name is Barnabas Katakwa','263732447112');
INSERT INTO CONTACT (EMAIL,FIRST_NAME,LAST_NAME,NOTES,PHONE) VALUES('tkaluzi@gmail.com','Tapiwa','Kaluzi','My Name is Tapiwa Katakwa','263732447112');

INSERT INTO ADDRESS(CITY,COUNTRY,STREET_NAME,STREET_NUMBER,SUBURB) VALUES('Harare','Zimbabwe','Gardenia',3,'Msasa Park');
INSERT INTO ADDRESS(CITY,COUNTRY,STREET_NAME,STREET_NUMBER,SUBURB) VALUES('Bulawayo','Zimbabwe','Ibhalabhala',11,'Selborne Park');
INSERT INTO ADDRESS(CITY,COUNTRY,STREET_NAME,STREET_NUMBER,SUBURB) VALUES('Gweru','Zimbabwe','South',6,'South Downs');
INSERT INTO ADDRESS(CITY,COUNTRY,STREET_NAME,STREET_NUMBER,SUBURB) VALUES('Johannesburg','South Africa','Gardenia',2,'Msasa Park');
INSERT INTO ADDRESS(CITY,COUNTRY,STREET_NAME,STREET_NUMBER,SUBURB) VALUES('Lusaka','Zambia','Gardenia',4,'Msasa Park');

UPDATE CONTACT SET ADDRESS_ID = 1 WHERE ID  = 1;
UPDATE CONTACT SET ADDRESS_ID = 2 WHERE ID  = 2;
UPDATE CONTACT SET ADDRESS_ID = 3 WHERE ID  = 3;
UPDATE CONTACT SET ADDRESS_ID = 4 WHERE ID  = 4;
UPDATE CONTACT SET ADDRESS_ID = 5 WHERE ID  = 5;
UPDATE CONTACT SET ADDRESS_ID = 1 WHERE ID  = 6;
UPDATE CONTACT SET ADDRESS_ID = 2 WHERE ID  = 7;
UPDATE CONTACT SET ADDRESS_ID = 3 WHERE ID  = 8;
UPDATE CONTACT SET ADDRESS_ID = 4 WHERE ID  = 9;
UPDATE CONTACT SET ADDRESS_ID = 5 WHERE ID  = 10;